spring:
  application:
    name: TaskManagement

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8080}

jwt:
  secretKey: ${JWT_SECRET}
  expirationTime: 3600000

frontend:
  url: ${FRONTEND_URL}